### ISSUE TITLE
API not sending JSON data

### ISSUE THREAD

**Issue by IV2KBMoFxYIA** [dxFeed/dxLink#7] opened 2024-04-25 20:24 UTC
Most of the time I am receiving JSON data through the API. However, same code, no changes, and sometimes I get a list of data instead. 

JSON: 
![image](https://github.com/dxFeed/dxLink/assets/13455248/73d48ebc-1502-441c-b754-d694bf3feec3)

LIST:
![image](https://github.com/dxFeed/dxLink/assets/13455248/96204411-b585-4dde-8a93-ef83b57a4c98)

According to the documentation, the API should always be sending JSON data.

**Comment by avil-jc01** [comment] 2024-04-29 13:36
Hello @IV2KBMoFxYIA  - I think you are having the same issue as me in #6  https://github.com/dxFeed/dxLink/issues/6 

When you are setting up the websocket connection, try printing to debug what the responses are to your messages. I bet you when you send CHANNEL_SETUP containing dataFormat = FULL, you are getting back COMPACT anyway.

**Comment by voros1** [comment] 2024-04-29 13:43
When I sent FEED_SETUP -> FULL (or when I don't), I seem to randomly get back FULL or COMPACT.  I can not find a pattern, but it does some like it happens in streaks.  I came across this in TT documentation:
![image](https://github.com/dxFeed/dxLink/assets/12551442/6a53905a-69ad-475a-936a-d2db7207951f)

I've decided to update my code to detect FULL vs COMPACT data and to properly handle both (ie, I manually deserialize the latter case).

**Comment by voros1** [comment] 2024-04-29 14:24
It's here:
https://developer.tastytrade.com/streaming-market-data/#get-api-quote-tokens (but this is behind a login wall, so probably not helpful)
The link in the screenshot goes here:
https://demo.dxfeed.com/dxlink-ws/debug/#/protocol (which doesn't say anything about that fact).
Interestingly, the demo console on that page does not appear to work for SETUP, and seems to be sending back FULL responses.
I really don't like it either - it's fine to have multiple formats, and I understand why COMPACT could be considered better.  But you can't just randomly switch back and forth minute by minute.

**Comment by avil-jc01** [comment] 2024-04-29 14:28
Yep I've seen that debug protocol page before, it definitely is a mock-up and not a true reference implementation - exactly as you describe. Nothing in the changelog(s) on dxfeed website either about dropping FULL support. 

Ah well. At least we can find each other and troubleshoot in Github.

**Comment by IV2KBMoFxYIA** [comment] 2024-04-29 15:07
Yea, I didn't even know the terms FULL and COMPACT. lol. I just saw that I was getting a different format and dealt with it. So yea I am handling both now and no issues.

**Comment by Fyzu** [comment] 2024-05-15 09:39
`FEED_SETUP` parameters are just a declaration of the desire of the client, the server notifies by `FEED_CONFIG` you in what format it will actually return the data.

Some endpoints may have stricter settings on the option to choose from.

To better understand the protocol, read the description [here](https://demo.dxfeed.com/dxlink-ws/debug/#/protocol)

**Comment by Fyzu** [comment] 2024-05-15 09:48
Share on which endpoints do you observe this behavior?

**Comment by Fyzu** [comment] 2024-05-15 09:49
@IV2KBMoFxYIA @voros1 @avil-jc01 Share on which endpoints do you observe this behavior?

**Comment by Fyzu** [comment] 2024-05-15 11:55
> > @IV2KBMoFxYIA @voros1 @avil-jc01 Share on which endpoints do you observe this behavior?
> 
> I am not sure what you mean by which endpoint? its the web socket connection.

Could you please provide the URL of the dxLink server you use when you observe this behavior? e.g. `wss://demo.dxfeed.com/dxlink-ws`

**Comment by voros1** [comment] 2024-05-15 12:56
I'm using wss://tasty-live-ws.dxfeed.com/realtime

>  the server notifies by FEED_CONFIG you in what format it will actually return the data.
Yes, but it was changing minute by minute.  I'd been happily using these endpoints for a long time with FULL, when I suddenly started getting COMPACT results.
These days, I simply detect the data type and use either.

**Comment by avil-jc01** [comment] 2024-05-15 13:29
>  FEED_SETUP parameters are just a declaration of the desire of the client, the server notifies by FEED_CONFIG you in what format it will actually return the data.

While this fully explains the unexpected behavior, nowhere in the documentation does it state that FEED_SETUP params are a "declaration of desire" - in base expectation in any client/server relationship is that either a) the server executes the client request or b) returns a sane error/warning/exception. It is in my opinion a bug to silently ignore or drop a submitted FEED_SETUP param request and continue with the transactions with no error message. 

Can you provide any other example of a reputable API behaving the same way: client requests params for future transactions and server silently ignores them (no error/warning/exception) and continues with some other params?

**Comment by voros1** [comment] 2024-05-15 13:37
As best as I can tell, FEED_SETUP does nothing.  In the demo console, pressing the Setup button literally does not send a message.

**Comment by Fyzu** [comment] 2024-05-15 13:43
> > FEED_SETUP parameters are just a declaration of the desire of the client, the server notifies by FEED_CONFIG you in what format it will actually return the data.
> 
> While this fully explains the unexpected behavior, nowhere in the documentation does it state that FEED_SETUP params are a "declaration of desire" - my base expectation in any client/server relationship is that either a) the server executes the client request or b) returns a sane error/warning/exception. It is in my opinion a bug to silently ignore or drop a submitted FEED_SETUP param request and continue with the transactions with no error message.
> 
> Can you provide any other example of a reputable API behaving the same way: client requests params for future transactions and server silently ignores them (no error/warning/exception) and continues with some other params?

Thank you for your feedback, we will add more explanation to the protocol description.

**Comment by Fyzu** [comment] 2024-05-15 13:43
> As best as I can tell, FEED_SETUP does nothing. In the demo console, pressing the Setup button literally does not send a message.

This is a known issue, and will be fixed in the next release.

**Comment by Fyzu** [comment] 2024-05-15 13:49
> I'm using wss://tasty-live-ws.dxfeed.com/realtime
> 
> > the server notifies by FEED_CONFIG you in what format it will actually return the data.
> > Yes, but it was changing minute by minute.  I'd been happily using these endpoints for a long time with FULL, when I suddenly started getting COMPACT results.
> > These days, I simply detect the data type and use either.

Thank you for your response! Unfortunately, the issue isn't related to dxLink.
Please reach out to the support team of the endpoint provider, as they might be able to assist you with this matter.

**Closed** 2024-06-28 11:55 UTC
Labels: question
